/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TD1Fonctionnelle.app;

import TD1Fonctionnelle.list.LinkedList;

import static TD1Fonctionnelle.utilities.StringUtils.join;
import static TD1Fonctionnelle.utilities.StringUtils.split;
import static TD1Fonctionnelle.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
